services:
  pgdb:
    image: agnohq/pgvector:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-ai}
      POSTGRES_PASSWORD: ${DB_PASS:-ai}
      POSTGRES_DB: ${DB_NAME:-ai}
    networks:
      - main_net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-agent-os}:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_USER: ${DB_USER:-ai}
      DB_PASS: ${DB_PASS:-ai}
      DB_NAME: ${DB_NAME:-ai}
      WAIT_FOR_DB: "True"
      PRINT_ENV_ON_LOAD: "True"
    networks:
      - main_net
    depends_on:
      - pgdb
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  main_net:

volumes:
  pgdata:
