chat:
  quick_prompts:
    # web-search-agent:
    #   - "What can you do?"
    #   - "What is currently happening in France?"
    #   - "What is the latest news on the stock market?"
    # agno-assist:
    #   - "What can you do?"
    #   - "What is the latest news on Agno?"
    #   - "Tell me about Agno's AgentOS"
    core-agent:
      - "Create a blockbuster movie script."
      - "Give me an exciting action movie storyline."
      - "Suggest a romantic comedy with 3 main characters."
